namespace SDL3.Enums; 
public enum MessageBoxButtons {
    YesNo = 0,
    YesNoCancel,
    Ok,
    OkCancel,
    AbortRetryIgnore,
    TryAgain,
    TryAgainCancel,
    ContinueCancel,
    RetryCancel,
    YesNoCancelRetry,
    YesNoCancelIgnore,
    HelpClose,
    ApplyCancel,
    SaveCancel,
    ResetCancel,
    RetryIgnoreAll,
    NoToAllCancel,
    YesToAllCancel,
}
