name: CI

on: [push, pull_request]

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - name: dotnet build SDL3.Core
      run: |
        dotnet build SDL3/SDL3.Core.csproj -c Debug
        dotnet build SDL3/SDL3.Core.csproj -c Release
